# -*- coding: utf-8 -*-
"""Ciclo01 - Resoluçao Problemas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xNlPz8Gq0I7ngUEk6MIH62Fx5M_wMRbE
"""

import pandas as pd
import numpy as np

data = pd.read_csv( '/content/AB_NYC_2019.csv')

data.head()

"""Calcular a media de todos os valores da media de aluguel de Nova York

1. Colunas que mostra o aluguel
2. Calcular a media dessa coluna
"""

preco_aluguel = data.loc[:, 'price' ]

np.mean(preco_aluguel)

"""Contar todos os nomes distintos que aparecem na coluna região

1. Selecionar a coluna região
2. Mostrar apenas os nomes não repetidos( unico)
"""

data.head()

regiao = data.loc[:, 'neighbourhood_group']

pd.unique (regiao)

"""Encontrar o valor maximo que contem os valores dos alugueis

1. Selecionar as colunas alugueis
2. Encontrar o valor maximo dessa coluna
"""

preco_aluguel = data.loc[:, 'price']

np.max( preco_aluguel)